# Generated by Django 5.2.3 on 2025-07-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_remove_is_completed_add_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='strategyphase',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='objective',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='strategyphase',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
