# Generated by Django 5.2.3 on 2025-06-14 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedesigndocument',
            name='html_content',
            field=models.TextField(blank=True, help_text='Full HTML content of the GDD'),
        ),
        migrations.AddField(
            model_name='gamedesigndocument',
            name='use_html_content',
            field=models.BooleanField(default=False, help_text='Use HTML content instead of structured fields'),
        ),
        migrations.CreateModel(
            name='GDDSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True)),
                ('section_id', models.CharField(help_text='Unique identifier for this section in the HTML document', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this section in the document')),
                ('gdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.gamedesigndocument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='gametask',
            name='gdd_section',
            field=models.ForeignKey(blank=True, help_text='GDD section this task is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.gddsection'),
        ),
    ]
