# Generated by Django 5.2.3 on 2025-06-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_gddfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametask',
            name='custom_type',
            field=models.CharField(blank=True, help_text="Custom task type when task_type is 'other'", max_length=100, null=True),
        ),
    ]
