# Generated by Django 5.2.3 on 2025-06-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_gametask_custom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameasset',
            name='subtype',
            field=models.CharField(blank=True, help_text='Subtype of the asset (e.g., character, environment, concept art)', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameasset',
            name='asset_type',
            field=models.CharField(choices=[('3d_model', '3D Model'), ('2d_image', '2D Image'), ('music', 'Music'), ('video', 'Video'), ('reference', 'Reference'), ('other', 'Other')], max_length=20),
        ),
    ]
