# Generated by Django 5.2.3 on 2025-06-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_gameasset_subtype_alter_gameasset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameasset',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Custom thumbnail image for this asset', null=True, upload_to='game_assets/thumbnails/'),
        ),
    ]
