# Generated by Django 5.2.3 on 2025-06-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_gameasset_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gddfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this feature within its section/subsection'),
        ),
        migrations.AddField(
            model_name='gddfeature',
            name='subsection_id',
            field=models.CharField(blank=True, help_text='ID of the subsection this feature belongs to', max_length=50, null=True),
        ),
        migrations.AlterModelOptions(
            name='gddfeature',
            options={'ordering': ['order', 'priority', 'feature_name']},
        ),
    ]
