# Generated by Django 4.2.10 on 2025-06-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_gddfeature_order_gddfeature_subsection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gddfeature',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this feature', null=True),
        ),
    ]
