# Generated by Django 4.2.10 on 2025-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_gddfeature_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametask',
            name='company_section',
            field=models.CharField(choices=[('game_development', 'Game Development'), ('education', 'Education'), ('arcade', 'Arcade'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('it', 'IT & Infrastructure'), ('research', 'Research & Development'), ('other', 'Other')], default='game_development', help_text='Company section this task belongs to', max_length=30),
        ),
    ]
