# Generated by Django 4.2.10 on 2025-06-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_gametask_company_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametask',
            name='campaign_id',
            field=models.CharField(blank=True, help_text='Marketing campaign ID this task is part of', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='channel',
            field=models.CharField(blank=True, help_text='Marketing channel (social media, email, events, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='course_id',
            field=models.CharField(blank=True, help_text='Course ID this task is related to', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='experiment_id',
            field=models.CharField(blank=True, help_text='ID of the experiment this task is part of', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='feature_id',
            field=models.CharField(blank=True, help_text='ID of the feature in the GDD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='hypothesis',
            field=models.TextField(blank=True, help_text='Hypothesis being tested in this research task', null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='learning_objective',
            field=models.TextField(blank=True, help_text='Learning objective this task addresses', null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the arcade machine', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='machine_id',
            field=models.CharField(blank=True, help_text='Arcade machine ID this task is for', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='maintenance_type',
            field=models.CharField(blank=True, help_text='Type of maintenance (repair, upgrade, cleaning, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='platform',
            field=models.CharField(blank=True, help_text='Platform this task is for (PC, mobile, console, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='research_area',
            field=models.CharField(blank=True, help_text='Area of research this task is related to', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Target audience for this educational task', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gametask',
            name='target_metrics',
            field=models.TextField(blank=True, help_text='Target metrics for this marketing task', null=True),
        ),
    ]
