# Generated by Django 4.2.10 on 2025-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_gametask_campaign_id_gametask_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gddfeature',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('to_do', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done')], db_column='status_value', default='backlog', max_length=20),
        ),
    ]
