# Generated by Django 5.2.3 on 2025-06-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_status_value_to_gddfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametask',
            name='game',
            field=models.ForeignKey(blank=True, help_text='Required for game development tasks, leave empty for other sections', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.gameproject', verbose_name='Associated Game'),
        ),
    ]
