# Generated by Django 4.2.10 on 2025-06-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_arcadetask_educationtask_gamedevelopmenttask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedevelopmenttask',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_tasks', to='projects.gameproject'),
        ),
    ]
