# Generated by Django 4.2.10 on 2025-07-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_team_arcadetask_team_educationtask_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcadetask',
            name='additional_note_text',
            field=models.TextField(blank=True, verbose_name='Note Details'),
        ),
        migrations.AddField(
            model_name='arcadetask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Additional Note'),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='additional_note_text',
            field=models.TextField(blank=True, verbose_name='Note Details'),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Additional Note'),
        ),
        migrations.AddField(
            model_name='gamedevelopmenttask',
            name='additional_note_text',
            field=models.TextField(blank=True, verbose_name='Note Details'),
        ),
        migrations.AddField(
            model_name='gamedevelopmenttask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Additional Note'),
        ),
        migrations.AddField(
            model_name='r1d3task',
            name='additional_note_text',
            field=models.TextField(blank=True, verbose_name='Note Details'),
        ),
        migrations.AddField(
            model_name='r1d3task',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Additional Note'),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='additional_note_text',
            field=models.TextField(blank=True, verbose_name='Note Details'),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Additional Note'),
        ),
        migrations.AddField(
            model_name='themeparktask',
            name='additional_note_text',
            field=models.TextField(blank=True, verbose_name='Note Details'),
        ),
        migrations.AddField(
            model_name='themeparktask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Additional Note'),
        ),
    ]
