# Generated by Django 4.2.10 on 2025-07-02 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0016_arcadetask_additional_note_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcadetask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add Subtasks'),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add Subtasks'),
        ),
        migrations.AddField(
            model_name='gamedevelopmenttask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add Subtasks'),
        ),
        migrations.AddField(
            model_name='r1d3task',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add Subtasks'),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add Subtasks'),
        ),
        migrations.AddField(
            model_name='themeparktask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add Subtasks'),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
                'ordering': ['created_at'],
            },
        ),
    ]
