# Generated by Django 4.2.10 on 2025-07-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_arcadetask_has_subtasks_educationtask_has_subtasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcadetask',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='gamedevelopmenttask',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='r1d3task',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='themeparktask',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='arcadetask',
            name='additional_note_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional note'),
        ),
        migrations.AlterField(
            model_name='arcadetask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Add additional note'),
        ),
        migrations.AlterField(
            model_name='arcadetask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add subtasks'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='additional_note_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional note'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Add additional note'),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add subtasks'),
        ),
        migrations.AlterField(
            model_name='gamedevelopmenttask',
            name='additional_note_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional note'),
        ),
        migrations.AlterField(
            model_name='gamedevelopmenttask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Add additional note'),
        ),
        migrations.AlterField(
            model_name='gamedevelopmenttask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add subtasks'),
        ),
        migrations.AlterField(
            model_name='r1d3task',
            name='additional_note_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional note'),
        ),
        migrations.AlterField(
            model_name='r1d3task',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Add additional note'),
        ),
        migrations.AlterField(
            model_name='r1d3task',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add subtasks'),
        ),
        migrations.AlterField(
            model_name='socialmediatask',
            name='additional_note_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional note'),
        ),
        migrations.AlterField(
            model_name='socialmediatask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Add additional note'),
        ),
        migrations.AlterField(
            model_name='socialmediatask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add subtasks'),
        ),
        migrations.AlterField(
            model_name='themeparktask',
            name='additional_note_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional note'),
        ),
        migrations.AlterField(
            model_name='themeparktask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Add additional note'),
        ),
        migrations.AlterField(
            model_name='themeparktask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add subtasks'),
        ),
    ]
