# Generated by Django 5.2.3 on 2025-07-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_merge_20250707_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcadetask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='educationtask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='gamedevelopmenttask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='r1d3task',
            name='team',
        ),
        migrations.RemoveField(
            model_name='socialmediatask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='themeparktask',
            name='team',
        ),
    ]
