# Generated by Django 5.2.3 on 2025-07-08 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_arcadetask_team_remove_educationtask_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcadetask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='projects.team'),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='projects.team'),
        ),
        migrations.AddField(
            model_name='gamedevelopmenttask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='projects.team'),
        ),
        migrations.AddField(
            model_name='r1d3task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='projects.team'),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='projects.team'),
        ),
        migrations.AddField(
            model_name='themeparktask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='projects.team'),
        ),
    ]
