# Generated by Django 5.2.3 on 2025-07-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_remove_team_from_r1d3task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcadetask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='educationtask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='gamedevelopmenttask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='socialmediatask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='themeparktask',
            name='team',
        ),
    ]
