# Generated by Django 4.2.10 on 2025-11-07 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0099_add_text_ownership_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('company_section', models.CharField(choices=[('r1d3', 'R1D3 System'), ('games', 'Game Development'), ('education', 'Education'), ('social_media', 'Social Media'), ('arcade', 'Arcade'), ('theme_park', 'Theme Park'), ('indie_news', 'Indie News')], max_length=50)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('owner_name', models.CharField(blank=True, default='', help_text='Epic owner/lead', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Epic',
                'verbose_name_plural': 'Epics',
                'ordering': ['-priority', 'target_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='arcadetask',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task (for subtask-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subtasks', to='projects.arcadetask'),
        ),
        migrations.AddField(
            model_name='arcadetask',
            name='task_level',
            field=models.CharField(choices=[('epic', 'Epic'), ('task', 'Task'), ('subtask', 'Subtask')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task (for subtask-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subtasks', to='projects.educationtask'),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='task_level',
            field=models.CharField(choices=[('epic', 'Epic'), ('task', 'Task'), ('subtask', 'Subtask')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='gamedevelopmenttask',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task (for subtask-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subtasks', to='projects.gamedevelopmenttask'),
        ),
        migrations.AddField(
            model_name='gamedevelopmenttask',
            name='task_level',
            field=models.CharField(choices=[('epic', 'Epic'), ('task', 'Task'), ('subtask', 'Subtask')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='r1d3task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task (for subtask-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subtasks', to='projects.r1d3task'),
        ),
        migrations.AddField(
            model_name='r1d3task',
            name='task_level',
            field=models.CharField(choices=[('epic', 'Epic'), ('task', 'Task'), ('subtask', 'Subtask')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task (for subtask-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subtasks', to='projects.socialmediatask'),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='task_level',
            field=models.CharField(choices=[('epic', 'Epic'), ('task', 'Task'), ('subtask', 'Subtask')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='themeparktask',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task (for subtask-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subtasks', to='projects.themeparktask'),
        ),
        migrations.AddField(
            model_name='themeparktask',
            name='task_level',
            field=models.CharField(choices=[('epic', 'Epic'), ('task', 'Task'), ('subtask', 'Subtask')], default='task', max_length=20),
        ),
        migrations.AlterField(
            model_name='arcadetask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='educationtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamedevelopmenttask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='r1d3task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialmediatask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='themeparktask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arcadetask',
            name='epic',
            field=models.ForeignKey(blank=True, help_text='Epic this task belongs to (for task-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tasks', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='educationtask',
            name='epic',
            field=models.ForeignKey(blank=True, help_text='Epic this task belongs to (for task-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tasks', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='gamedevelopmenttask',
            name='epic',
            field=models.ForeignKey(blank=True, help_text='Epic this task belongs to (for task-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tasks', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='r1d3task',
            name='epic',
            field=models.ForeignKey(blank=True, help_text='Epic this task belongs to (for task-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tasks', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='socialmediatask',
            name='epic',
            field=models.ForeignKey(blank=True, help_text='Epic this task belongs to (for task-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tasks', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='themeparktask',
            name='epic',
            field=models.ForeignKey(blank=True, help_text='Epic this task belongs to (for task-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tasks', to='projects.epic'),
        ),
    ]
