# Generated by Django 4.2.10 on 2025-11-07 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0100_epic_arcadetask_parent_task_arcadetask_task_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameproject',
            name='lead_artist_name',
            field=models.CharField(blank=True, help_text='Lead artist name', max_length=100),
        ),
        migrations.AddField(
            model_name='gameproject',
            name='lead_designer_name',
            field=models.CharField(blank=True, help_text='Lead designer name', max_length=100),
        ),
        migrations.AddField(
            model_name='gameproject',
            name='lead_developer_name',
            field=models.CharField(blank=True, help_text='Lead developer name', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameproject',
            name='lead_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_directed_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameproject',
            name='lead_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameproject',
            name='lead_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
