# Generated by Django 4.2.10 on 2025-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_add_text_lead_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameproject',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive this game project'),
        ),
    ]
