# Generated by Django 5.2.3 on 2025-07-10 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('central_theme', models.CharField(max_length=255, verbose_name='Central Theme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.TextField(verbose_name='Document Objective')),
                ('summary', models.TextField(verbose_name='Theme Summary')),
                ('introduction', models.TextField(verbose_name='Introduction to Theme')),
                ('practical_applications', models.TextField(verbose_name='Practical Applications')),
                ('recommended_resources', models.TextField(blank=True, verbose_name='Recommended Resources')),
                ('attachments', models.TextField(blank=True, help_text='Links to exercises, important resources, etc.', verbose_name='Attachments')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Concept Name')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('detailed_explanation', models.TextField(verbose_name='Detailed Explanation')),
                ('illustrative_example', models.TextField(verbose_name='Illustrative Example')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='education.course')),
            ],
            options={
                'verbose_name': 'Concept Section',
                'verbose_name_plural': 'Concept Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedTopicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Topic Name')),
                ('applications', models.TextField(verbose_name='Applications')),
                ('challenges', models.TextField(verbose_name='Risks/Challenges')),
                ('real_example', models.TextField(verbose_name='Real-world Example')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_topics', to='education.course')),
            ],
            options={
                'verbose_name': 'Advanced Topic',
                'verbose_name_plural': 'Advanced Topics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Term')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='education.course')),
            ],
            options={
                'verbose_name': 'Glossary Term',
                'verbose_name_plural': 'Glossary Terms',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='PracticalExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Example Title')),
                ('code', models.TextField(blank=True, verbose_name='Code')),
                ('image', models.URLField(blank=True, verbose_name='Image URL')),
                ('step_by_step', models.TextField(verbose_name='Step-by-step Explanation')),
                ('real_application', models.TextField(blank=True, verbose_name='Application in Real Project')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_examples', to='education.course')),
            ],
            options={
                'verbose_name': 'Practical Example',
                'verbose_name_plural': 'Practical Examples',
                'ordering': ['order'],
            },
        ),
    ]
