# Generated by Django 5.2.3 on 2025-07-11 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_conceptsection_advancedtopicsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='education.knowledgecategory'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief summary of the article'),
        ),
    ]
