# Generated by Django 5.2.3 on 2025-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_knowledgearticle_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='content_blocks',
            field=models.JSONField(blank=True, help_text='JSON content blocks data', null=True),
        ),
    ]
