# Generated by Django 4.2.10 on 2025-06-28 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndieTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField()),
                ('tool_type', models.CharField(choices=[('engine', 'Game Engine'), ('graphics', 'Graphics Tool'), ('audio', 'Audio Tool'), ('modeling', '3D Modeling'), ('animation', 'Animation Tool'), ('ide', 'Development Environment'), ('framework', 'Framework/Library'), ('asset', 'Asset Store/Pack'), ('productivity', 'Productivity Tool'), ('other', 'Other')], max_length=50)),
                ('pricing_model', models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('subscription', 'Subscription'), ('one_time', 'One-time Purchase'), ('open_source', 'Open Source')], max_length=50)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('windows_support', models.BooleanField(default=True)),
                ('mac_support', models.BooleanField(default=False)),
                ('linux_support', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('has_review', models.BooleanField(default=False)),
                ('review_url', models.URLField(blank=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indie Tool',
                'verbose_name_plural': 'Indie Tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndieNewsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('to_do', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='to_do', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('actual_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('task_type', models.CharField(blank=True, max_length=100)),
                ('article_id', models.CharField(blank=True, max_length=100)),
                ('news_type', models.CharField(blank=True, choices=[('review', 'Game Review'), ('preview', 'Game Preview'), ('interview', 'Developer Interview'), ('feature', 'Feature Article'), ('news', 'News Article'), ('opinion', 'Opinion Piece'), ('guide', 'Game Guide')], max_length=100)),
                ('developer', models.CharField(blank=True, max_length=255)),
                ('game_title', models.CharField(blank=True, max_length=255)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indie News Task',
                'verbose_name_plural': 'Indie News Tasks',
            },
        ),
        migrations.CreateModel(
            name='IndieGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('platforms', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('website', models.URLField(blank=True)),
                ('steam_url', models.URLField(blank=True)),
                ('itch_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='indie_games/covers/')),
                ('trailer_url', models.URLField(blank=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('review_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_url', models.URLField(blank=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indie Game',
                'verbose_name_plural': 'Indie Games',
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='IndieEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('showcase', 'Game Showcase'), ('competition', 'Competition'), ('awards', 'Awards Ceremony'), ('meetup', 'Developer Meetup'), ('jam', 'Game Jam'), ('expo', 'Expo/Convention'), ('other', 'Other')], max_length=50)),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('ticket_url', models.URLField(blank=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_covered', models.BooleanField(default=False)),
                ('coverage_url', models.URLField(blank=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indie Event',
                'verbose_name_plural': 'Indie Events',
                'ordering': ['start_date', 'name'],
            },
        ),
    ]
