# Generated by Django 5.2.3 on 2025-07-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indienewstask',
            name='additional_note_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional note'),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Add additional note'),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add subtasks'),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
    ]
