# Generated by Django 4.2.10 on 2025-07-02 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indienewstask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='projects.team'),
        ),
    ]
