# Generated by Django 4.2.10 on 2025-07-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0002_indienewstask_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='indienewstask',
            name='additional_note_text',
            field=models.TextField(blank=True, verbose_name='Note Details'),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Additional Note'),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add Subtasks'),
        ),
    ]
