# Generated by Django 5.2.3 on 2025-07-08 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0002_indienewstask_additional_note_text_and_more'),
        ('projects', '0021_add_team_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='indienewstask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='projects.team'),
        ),
    ]
