# Generated by Django 4.2.10 on 2025-07-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0003_indienewstask_additional_note_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indienewstask',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='indienewstask',
            name='additional_note_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional note'),
        ),
        migrations.AlterField(
            model_name='indienewstask',
            name='has_additional_note',
            field=models.BooleanField(default=False, verbose_name='Add additional note'),
        ),
        migrations.AlterField(
            model_name='indienewstask',
            name='has_subtasks',
            field=models.BooleanField(default=False, verbose_name='Add subtasks'),
        ),
    ]
