# Generated by Django 5.2.3 on 2025-07-08 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0003_add_team_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indienewstask',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_indie_news_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
