# Generated by Django 4.2.10 on 2025-11-07 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_epic_arcadetask_parent_task_arcadetask_task_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indie_news', '0004_add_assigned_users_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indienewstask',
            name='team',
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='assigned_to_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='epic',
            field=models.ForeignKey(blank=True, help_text='Epic this task belongs to (for task-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tasks', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task (for subtask-level items)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subtasks', to='indie_news.indienewstask'),
        ),
        migrations.AddField(
            model_name='indienewstask',
            name='task_level',
            field=models.CharField(choices=[('epic', 'Epic'), ('task', 'Task'), ('subtask', 'Subtask')], default='task', max_length=20),
        ),
        migrations.AlterField(
            model_name='indienewstask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
