# Generated by Django 5.2.3 on 2025-07-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0005_merge_20250707_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indienewstask',
            name='team',
        ),
    ]
