# Generated by Django 4.2.10 on 2025-07-02 02:22
# Modified to fix migration conflicts with projects app rename

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0001_initial'),
    ]

    operations = [
        # Removed AddField operation to avoid dependency on projects.team
        # This is a dummy operation that will be replaced by migration 0006
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
