# Generated by Django 5.2.3 on 2025-07-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indie_news', '0005_merge_20250707_1845'),
    ]

    operations = [
        # Replaced RemoveField with a dummy operation since the field doesn't exist
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
